# The URL the site will be built for
base_url = "https://toucan.coinduf.eu/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
[markdown]
highlight_code = true
highlight_theme = "base16-ocean-light"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[extra]
# Put all your custom variables here
title = "Toucan theme"
title_pic = "/favicon.ico"
description = "Theme for Zola inspired from Pelican website theme"
license = """Content under <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA</a> Licence"""

[extra.theme]
read_more = "Read more"